parameters:
  GitHubConnection: "" # defaults for any parameters that aren't specified
  releaseNotesFilePath: ""
  addChangeLog: true
  isPreRelease: false
  isDraft: false
  tagSource: "gitTag"
  action: create
  target: $(Build.SourceVersion)

jobs:
  - job: Create_Github_Release
    timeoutInMinutes: 30 # timeout on job if deploy is not completed in 30 minutes
    pool:
      vmImage: ubuntu-16.04
    steps:
      - checkout: none # we already have the artifacts built, don't need the code
      - download: current

      - task: GitHubRelease@1
        displayName: "GitHub release ${{ parameters.action }}"
        inputs:
          action: ${{ parameters.action }}
          gitHubConnection: ${{ parameters.GitHubConnection }}
          repositoryName: "$(Build.Repository.Name)"
          releaseNotesFilePath: ${{ parameters.releaseNotesFilePath }}
          target: ${{ parameters.target }}
          assets: |
            $(Agent.BuildDirectory)/dist/spk-linux
            $(Agent.BuildDirectory)/dist/spk-macos
            $(Agent.BuildDirectory)/dist/spk-win.exe
          tagSource: ${{ parameters.tagSource }}
          isDraft: ${{ parameters.isDraft }}
          isPreRelease: ${{ parameters.isPrelease }}
          addChangeLog: ${{ parameters.addChangeLog }}
